version: '3'
services:
  postgres_db:
    image: postgres
    hostname: db
    volumes:
      - "./postgres-data/:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    networks:
      - salt
  redis_cache:
    image: redis:4-alpine
    hostname: redis
    volumes:
      - "./redis-data/:/var/lib/redis"
    ports:
      - 6379:6379
    networks:
      - salt
  http:
    build: 
      context: .
    hostname: http
    working_dir: /code
    volumes:
      - "./code/:/code"
#    entrypoint: /usr/local/bin/python3 /usr/local/bin/gunicorn --bind 0.0.0.0:8000 helloworld.wsgi
    entrypoint: gunicorn --bind 0.0.0.0:8000 helloworld.wsgi
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
    networks:
      - salt
# salt network is an overlay network
networks:
  salt:
    external: true
